name: CI
on: [ push, pull_request ]

jobs:
  testAndLint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node:
          - '14'
          - '16'
          - '18'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@10693b3829bf86eb2572aef5f3571dcf5ca9287d # v2.2.2
        with:
          version: ^7.11.0
          run_install: true

      - run: pnpm test
      - run: pnpm lint
